### ISSUE TITLE
exclude paths with affiliateCode parameter from fastly caching

### ISSUE THREAD

**Issue by m-waes** [shopware/recipes#114]
This repo is deprecated: https://github.com/shopware/paas?tab=readme-ov-file#this-repository-is-deprecated

Before opening [this PR](https://github.com/shopware/paas/pull/19/files) here again, I wanted to ask, if it would be accepted in the first place.

**Comment by shyim** [comment]
Yes

**Comment by shyim** [comment]
is merged
