### ISSUE TITLE
Usage of STOREFRONT_PROXY_URL

### ISSUE THREAD

**Issue by PheysX** [shopware/recipes#126]
Heyho, im not sure but it seems like the env variable `STOREFRONT_PROXY_URL` is not used at all. Everywhere is called PROXY_URL.

**Comment by shyim** [comment]
good catch. do you want to open a PR?

**Comment by PheysX** [comment]
Sure, should I change it all to STOREFRONT_PROXY_URL? Shopware is using PROXY_URL at the moment. Or should I change it to STOREFRONT_PROXY_URL here and in shopware/shopware?

**Comment by shyim** [comment]
i would name it PROXY_URL as it is in shopware itself. changing the env var is annoying 😅
