### ISSUE TITLE
gitignore custom/*

### ISSUE THREAD

**Issue by RafaelKr** [shopware/recipes#134]
#89 removed the gitignore for
```
custom/*
!custom/plugins/.gitkeep
!custom/static-plugins/
```

Is there a specific reason for that or was it accidentally?

CC @ioanok @shyim

**Comment by shyim** [comment]
so you can commit your plugins and static plugins? 🤔 

whats the problem?

**Comment by RafaelKr** [comment]
cc @haebich (you commented on #89)
