### ISSUE TITLE
pentatrion vite bundle config conflicts with ShopwareAdministration bundle

### ISSUE THREAD

**Issue by raffaelecarelle** [shopware/recipes#143]
`{
    "bundles": {
        "Pentatrion\\ViteBundle\\PentatrionViteBundle": [
            "all"
        ]
    }
}
`

The recipe above conflicts with 

`public function getAdditionalBundles(AdditionalBundleParameters $parameters): array
    {
        return [
            new PentatrionViteBundle(),
        ];
    }`

under  Shopware\Administration\Administration

**Comment by shyim** [comment]
Update to Shopware 6.6.8.1

**Comment by raffaelecarelle** [comment]
Ok thank you
