### ISSUE TITLE
SHOPWARE_CDN_STRATEGY_DEFAULT changed from `id` to `physical_filename`

### ISSUE THREAD

**Issue by RafaelKr** [shopware/recipes#25]
I had a Shopware 6.4.12.0 shop. I now first did an update to 6.4.17.0 and then migrated to Symfony flex as described in the docs https://developer.shopware.com/docs/guides/installation/flex#how-to-migrate-from-production-template-to-symfony-flex

Now all my images were missing. Turns out Shopware was using `shopware.cdn.strategy` `physical_filename` because that was set in the `config/services.yaml`. The previous env file had the line `SHOPWARE_CDN_STRATEGY_DEFAULT=id` included.

The shop was initially installed with the command
```bash
bin/console system:setup --no-interaction \
      --database-url='mysql://user:pass@localhost:3306/shopware' \
      --app-env='prod' \
      --app-url='https://example.com'
```

So the solution was to set `SHOPWARE_CDN_STRATEGY_DEFAULT=id` in the .env again.

This should be
a) noted in the migration guide and
b) it should be thought about what the default strategy should be

**Comment by shyim** [comment]
The new updater will rename the existing .env to `.env.local`. So this should work then right?

**Comment by RafaelKr** [comment]
Should be working then.
Can I ask why the move from id to physical_filename was done?

**Comment by shyim** [comment]
I have no idea. It's a long-standing change which was only in production template

**Comment by shyim** [comment]
I close this then
