### ISSUE TITLE
devenv recipe problems on macOs

### ISSUE THREAD

**Issue by 0x4** [shopware/recipes#29]
The devenv recipe contains 

`sleep infinity`

in the devenv.nix entryscript - but this dont't work with newer macOs versions (tested with Ventura)

I switched to 

`sleep 2147483647`

but I don't know if there is a better solution for that. 

I'm new to devenv / nixos - not sure if there is another way to implement this without using this blocking command which seems a little bit unusual for me.

**Comment by shyim** [comment]
Ahh that is fixed already. Just run `devenv update` and then it should work

**Comment by shyim** [comment]
should be fixed with https://github.com/shopware/recipes/commit/789a34509e60807a14e35eac65f653152ba35cbb
