### ISSUE TITLE
For PaaS, the public media and thumbnail directories need to be network mounts to work with worker nodes

### ISSUE THREAD

**Issue by emmer91** [shopware/recipes#30]
Worker nodes don't have access to local mounts. Only the app has access to them. So for a standard implementation, these mounts need to be network mounts for the thumbnail generation via the queue (worker nodes)

https://github.com/shopware/recipes/blob/e8f716580b865cf37309a1aabf220975ce9d91de/shopware/paas-meta/6.4/.platform/applications.yaml#L161-L166

Documentation about network mounts at PSH: https://docs.platform.sh/add-services/network-storage.html

**Comment by shyim** [comment]
but only on grid right?

**Comment by emmer91** [comment]
should also be relevant for dedicated 3

**Comment by runelaenen** [comment]
This issue can be closed as it was changed in my latest PR
