### ISSUE TITLE
After composer recipe:update the services.yaml are corrupted

### ISSUE THREAD

**Issue by MBDealer** [shopware/recipes#31]
After composer recipe:update the services.yaml are corrupted and I have to fix it like this:

![Screenshot 17 01 2023 um 15 29 42 PM](https://user-images.githubusercontent.com/13245562/212925690-1c2c77dc-b751-4c03-8f93-765f6f11f90b.png)

**Comment by MBDealer** [comment]
[symfony.lock.txt](https://github.com/shopware/recipes/files/10436078/symfony.lock.txt)

**Comment by shyim** [comment]
This seems happened because we changed the line endings. This should not happen on any next update anymore.
