### ISSUE TITLE
Build Scripts in recipes for shopware/platform use wrong path of administration and storefront

### ISSUE THREAD

**Issue by JanRogge** [shopware/recipes#48]
Both the `build-administration` and `build-storefront` as well as the watch scripts are currently broken as they are trying to find the bundle under `vendor/shopware/X`.
But in a setup with platform they should  use `vendor/shopware/platform/src/X` as a path.

**Comment by shyim** [comment]
Feel free to make a PR, but it is not intended to use directly the mono repository and our recommended way are the splits. Is there are specific reason why you use that?

**Comment by JanRogge** [comment]
Yes i know that the other way is the recommended path but we currently use the monorepo for some development purposes and it should atleast work out of the box even if it is not the recommended way.

**Comment by shyim** [comment]
I fixed that in the meanwhile.
