### ISSUE TITLE
[flex] Better documentation, no config/README.md

### ISSUE THREAD

**Issue by vardumper** [shopware/recipes#5]
* I would like to know more about how to define/use build-only requirements. The README or docs don't tell. (at least I haven't been able to find info on that quickly).
* the main README points to a config/README.md which isn't part of the repo nor does it exist after install/project creation.
* add info on the admin user credentials

**Comment by shyim** [comment]
The new documentation should be only on the actual website and the flex recipe should give some starter info.

https://github.com/shopware/docs/blob/flex/guides/installation/flex.md

Feel free to make a PR to add here the user credentials: https://github.com/shopware/recipes/blob/main/shopware/core/6.4/post-install.txt

**Comment by vardumper** [comment]
where shall I create a PR? in recipes repo?

**Comment by shyim** [comment]
It's added here already https://github.com/shopware/recipes/blob/main/shopware/core/6.4/post-install.txt#L6
