### ISSUE TITLE
phpstan-bootstrap.php for frosh/code-quality-meta is missing

### ISSUE THREAD

**Issue by M-arcus** [shopware/recipes#54]
https://github.com/shopware/recipes/blob/f1333b58e0fc42be3b2b953dd9649901d05ab988/frosh/code-quality-meta/0.1/root/phpstan.neon.dist#L12

This file does not exist in the repo.

**Comment by shyim** [comment]
@stefanpoensgen fyi

**Comment by stefanpoensgen** [comment]
🤔 https://github.com/FriendsOfShopware/code-quality-meta/blob/main/phpstan-bootstrap.php

**Comment by M-arcus** [comment]
@stefanpoensgen my mistake, I was checking only the sub-dirs of https://github.com/shopware/recipes/tree/main/frosh/code-quality-meta
