### ISSUE TITLE
[flex] Attempted to load class "Factory" from namespace "Faker" when running demo data command

### ISSUE THREAD

**Issue by vardumper** [shopware/recipes#7]
### PHP Version

8.1.11

### Shopware Version

flex

### Expected behaviour

Demodata is installed.

### Actual behaviour

Exception is thrown.

### How to reproduce

Run APP_ENV=prod bin/console framework:demodata

**Comment by shyim** [comment]
I would add a proper check to the DemoDataCommand that this packages are missing. I would not like to have it also in production code. Do you maybe want to make a PR?

**Comment by shyim** [comment]
Is fixed with 6.4.17.0
https://github.com/shopware/platform/commit/9f09353cf5dd706a4d8bcad4446b017ac3aea973
